In [1]:
import cv2

# Read image
img = cv2.imread('nishaCV.png')
print(img)
print(type(img))

[[[215 226 204]
  [213 225 204]
  [214 225 203]
  ...
  [214 225 203]
  [214 224 204]
  [216 227 206]]

 [[214 225 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 204]
  [215 225 204]
  [215 226 204]]

 [[214 226 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 203]
  [214 225 204]
  [214 225 204]]

 ...

 [[216 223 229]
  [216 222 229]
  [217 223 230]
  ...
  [231 235 239]
  [232 236 239]
  [233 237 240]]

 [[216 222 229]
  [216 223 229]
  [216 223 229]
  ...
  [231 236 238]
  [231 236 239]
  [234 238 241]]

 [[215 222 228]
  [216 222 229]
  [216 222 229]
  ...
  [232 237 239]
  [231 235 238]
  [231 235 238]]]
<class 'numpy.ndarray'>


In [2]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray_image',gray_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()

In [4]:
hsv_img=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv_image',hsv_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()