In [1]:
# pip install opencv-python

Opencv phle c++ mei likha hua tha

In [2]:
import cv2

# Read image
img = cv2.imread('nishaCV.png')
print(img)
print(type(img))
# <class 'numpy.ndarray'> stored in numpy array



[[[215 226 204]
  [213 225 204]
  [214 225 203]
  ...
  [214 225 203]
  [214 224 204]
  [216 227 206]]

 [[214 225 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 204]
  [215 225 204]
  [215 226 204]]

 [[214 226 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 203]
  [214 225 204]
  [214 225 204]]

 ...

 [[216 223 229]
  [216 222 229]
  [217 223 230]
  ...
  [231 235 239]
  [232 236 239]
  [233 237 240]]

 [[216 222 229]
  [216 223 229]
  [216 223 229]
  ...
  [231 236 238]
  [231 236 239]
  [234 238 241]]

 [[215 222 228]
  [216 222 229]
  [216 222 229]
  ...
  [232 237 239]
  [231 235 238]
  [231 235 238]]]
<class 'numpy.ndarray'>


In [3]:
# Display image
cv2.imshow('My Image', img)
cv2.waitKey(0)  
cv2.destroyAllWindows()

## Image Properties


In [4]:
print("Shape:", img.shape)        # (height, width, channels)
print("Size:", img.size)          # Total pixels
print("Data Type:", img.dtype)

Shape: (1088, 844, 3)
Size: 2754816
Data Type: uint8


## Common Operations
<br> Resize, Crop, and Rotate

In [16]:
import cv2
import numpy as np

# Read the original image
img = cv2.imread('nishaCV.png')

# Make copies to manipulate channels separately
blue_removed = img.copy()
blue_removed[:, :, 0] = 0  # Remove blue

green_removed = img.copy()
green_removed[:, :, 1] = 0  # Remove green

red_removed = img.copy()
red_removed[:, :, 2] = 0  # Remove red

# Horizontally stack them for visualization
new_img = np.hstack((blue_removed, green_removed, red_removed))

# Show result
cv2.imshow('Channel Manipulation', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Manipulating on grey image [Grayscale view of Blue channel,green and red ]

In [20]:
import cv2
import numpy as np

# Read the original image
img = cv2.imread('nishaCV.png')

# Make copies to manipulate channels separately
# blue_removed = img.copy()
blue_removed=img[:, :, 0]# Remove blue

# green_removed = img.copy()
green_removed=img[:, :, 1]   # Remove green

# red_removed = img.copy()
red_removed=img[:, :, 2] # Remove red

# Horizontally stack them for visualization
new_img = np.hstack((blue_removed, green_removed, red_removed))

# Show result
cv2.imshow('Channel Manipulation', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()