In [1]:
# pip install opencv-python

Opencv phle c++ mei likha hua tha

In [2]:
import cv2

# Read image
img = cv2.imread('nishaCV.png')
print(img)
print(type(img))
# <class 'numpy.ndarray'> stored in numpy array



[[[215 226 204]
  [213 225 204]
  [214 225 203]
  ...
  [214 225 203]
  [214 224 204]
  [216 227 206]]

 [[214 225 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 204]
  [215 225 204]
  [215 226 204]]

 [[214 226 203]
  [214 225 203]
  [214 225 203]
  ...
  [214 225 203]
  [214 225 204]
  [214 225 204]]

 ...

 [[216 223 229]
  [216 222 229]
  [217 223 230]
  ...
  [231 235 239]
  [232 236 239]
  [233 237 240]]

 [[216 222 229]
  [216 223 229]
  [216 223 229]
  ...
  [231 236 238]
  [231 236 239]
  [234 238 241]]

 [[215 222 228]
  [216 222 229]
  [216 222 229]
  ...
  [232 237 239]
  [231 235 238]
  [231 235 238]]]
<class 'numpy.ndarray'>


In [3]:
# Display image
cv2.imshow('My Image', img)
cv2.waitKey(0)  
cv2.destroyAllWindows()

## Image Properties


In [4]:
print("Shape:", img.shape)        # (height, width, channels)
print("Size:", img.size)          # Total pixels
print("Data Type:", img.dtype)

Shape: (1088, 844, 3)
Size: 2754816
Data Type: uint8


## Common Operations
<br> Resize, Crop, and Rotate

In [ ]:


# Crop
cropped = img[50:200, 100:300]

# Rotate
rotated = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

In [ ]:
# cv2.imshow('resize',resized)

## To convert colored image to gray scale image

In [7]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray_image',gray_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()

In [16]:
import cv2
import numpy as np

# Read the original image
img = cv2.imread('nishaCV.png')

# Make copies to manipulate channels separately
blue_removed = img.copy()
blue_removed[:, :, 0] = 0  # Remove blue

green_removed = img.copy()
green_removed[:, :, 1] = 0  # Remove green

red_removed = img.copy()
red_removed[:, :, 2] = 0  # Remove red

# Horizontally stack them for visualization
new_img = np.hstack((blue_removed, green_removed, red_removed))

# Show result
cv2.imshow('Channel Manipulation', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Manipulating on grey image [Grayscale view of Blue channel,green and red ]

In [20]:
import cv2
import numpy as np

# Read the original image
img = cv2.imread('nishaCV.png')

# Make copies to manipulate channels separately
# blue_removed = img.copy()
blue_removed=img[:, :, 0]# Remove blue

# green_removed = img.copy()
green_removed=img[:, :, 1]   # Remove green

# red_removed = img.copy()
red_removed=img[:, :, 2] # Remove red

# Horizontally stack them for visualization
new_img = np.hstack((blue_removed, green_removed, red_removed))

# Show result
cv2.imshow('Channel Manipulation', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:

# Resize
resized = cv2.resize(img, (300, 300))
cv2.imshow('resize_img',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# flip image
img_flip=cv2.flip(img,0)
# horizontal_img_flip=cv2.flip(img,1)----------.img ko horizontally flip kregaa
cv2.imshow('flip_img',img_flip)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# cropping
img_crop=img[100:300,200:400]
# 100:300--height
# 200:400--breadth
cv2.imshow('crop_img',img_crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
# to save an img
cv2.imwrite('crop_img.png',img_crop)

True

In [32]:
import cv2
import numpy as np

# Create a blank black image (512x512 with 3 color channels)
img3 = np.zeros((512, 512, 3), dtype=np.uint8)

# Draw a filled rectangle
cv2.rectangle(img3, pt1=(100, 100), pt2=(300, 300), color=(255, 0, 0), thickness=0)

# Draw a filled circle
# 0 krne se emplty fill or -1 krne se fill hojayega andr
cv2.circle(img3, center=(100, 400), radius=50, color=(0, 0, 255), thickness=-1)

# Draw a line
cv2.line(img3, pt1=(0, 0), pt2=(512, 512), thickness=2, color=(0, 255, 0))

# Put text on the image
cv2.putText(img3, 
            text="Hello", 
            org=(100, 100), 
            fontScale=4, 
            color=(0, 255, 255), 
            thickness=2, 
            lineType=cv2.LINE_AA, 
            fontFace=cv2.FONT_ITALIC)

# Display the image
cv2.imshow("window", img3)
cv2.waitKey(0)
cv2.destroyAllWindows()
